// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Polarishq/log4nova (interfaces: INovaLogger)

package mock_log4nova

import (
	log4nova "github.com/Polarishq/log4nova"
	logrus "github.com/sirupsen/logrus"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockINovaLogger is a mock of INovaLogger interface
type MockINovaLogger struct {
	ctrl     *gomock.Controller
	recorder *MockINovaLoggerMockRecorder
}

// MockINovaLoggerMockRecorder is the mock recorder for MockINovaLogger
type MockINovaLoggerMockRecorder struct {
	mock *MockINovaLogger
}

// NewMockINovaLogger creates a new mock instance
func NewMockINovaLogger(ctrl *gomock.Controller) *MockINovaLogger {
	mock := &MockINovaLogger{ctrl: ctrl}
	mock.recorder = &MockINovaLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockINovaLogger) EXPECT() *MockINovaLoggerMockRecorder {
	return _m.recorder
}

// Debug mocks base method
func (_m *MockINovaLogger) Debug(_param0 ...interface{}) {
	_s := []interface{}{}
	for _, _x := range _param0 {
		_s = append(_s, _x)
	}
	_m.ctrl.Call(_m, "Debug", _s...)
}

// Debug indicates an expected call of Debug
func (_mr *MockINovaLoggerMockRecorder) Debug(arg0 ...interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Debug", reflect.TypeOf((*MockINovaLogger)(nil).Debug), arg0...)
}

// Debugf mocks base method
func (_m *MockINovaLogger) Debugf(_param0 string, _param1 ...interface{}) {
	_s := []interface{}{_param0}
	for _, _x := range _param1 {
		_s = append(_s, _x)
	}
	_m.ctrl.Call(_m, "Debugf", _s...)
}

// Debugf indicates an expected call of Debugf
func (_mr *MockINovaLoggerMockRecorder) Debugf(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	_s := append([]interface{}{arg0}, arg1...)
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Debugf", reflect.TypeOf((*MockINovaLogger)(nil).Debugf), _s...)
}

// Error mocks base method
func (_m *MockINovaLogger) Error(_param0 ...interface{}) {
	_s := []interface{}{}
	for _, _x := range _param0 {
		_s = append(_s, _x)
	}
	_m.ctrl.Call(_m, "Error", _s...)
}

// Error indicates an expected call of Error
func (_mr *MockINovaLoggerMockRecorder) Error(arg0 ...interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Error", reflect.TypeOf((*MockINovaLogger)(nil).Error), arg0...)
}

// Errorf mocks base method
func (_m *MockINovaLogger) Errorf(_param0 string, _param1 ...interface{}) {
	_s := []interface{}{_param0}
	for _, _x := range _param1 {
		_s = append(_s, _x)
	}
	_m.ctrl.Call(_m, "Errorf", _s...)
}

// Errorf indicates an expected call of Errorf
func (_mr *MockINovaLoggerMockRecorder) Errorf(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	_s := append([]interface{}{arg0}, arg1...)
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Errorf", reflect.TypeOf((*MockINovaLogger)(nil).Errorf), _s...)
}

// Info mocks base method
func (_m *MockINovaLogger) Info(_param0 ...interface{}) {
	_s := []interface{}{}
	for _, _x := range _param0 {
		_s = append(_s, _x)
	}
	_m.ctrl.Call(_m, "Info", _s...)
}

// Info indicates an expected call of Info
func (_mr *MockINovaLoggerMockRecorder) Info(arg0 ...interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Info", reflect.TypeOf((*MockINovaLogger)(nil).Info), arg0...)
}

// Infof mocks base method
func (_m *MockINovaLogger) Infof(_param0 string, _param1 ...interface{}) {
	_s := []interface{}{_param0}
	for _, _x := range _param1 {
		_s = append(_s, _x)
	}
	_m.ctrl.Call(_m, "Infof", _s...)
}

// Infof indicates an expected call of Infof
func (_mr *MockINovaLoggerMockRecorder) Infof(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	_s := append([]interface{}{arg0}, arg1...)
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Infof", reflect.TypeOf((*MockINovaLogger)(nil).Infof), _s...)
}

// SetDebug mocks base method
func (_m *MockINovaLogger) SetDebug() {
	_m.ctrl.Call(_m, "SetDebug")
}

// SetDebug indicates an expected call of SetDebug
func (_mr *MockINovaLoggerMockRecorder) SetDebug() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "SetDebug", reflect.TypeOf((*MockINovaLogger)(nil).SetDebug))
}

// SetError mocks base method
func (_m *MockINovaLogger) SetError() {
	_m.ctrl.Call(_m, "SetError")
}

// SetError indicates an expected call of SetError
func (_mr *MockINovaLoggerMockRecorder) SetError() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "SetError", reflect.TypeOf((*MockINovaLogger)(nil).SetError))
}

// SetInfo mocks base method
func (_m *MockINovaLogger) SetInfo() {
	_m.ctrl.Call(_m, "SetInfo")
}

// SetInfo indicates an expected call of SetInfo
func (_mr *MockINovaLoggerMockRecorder) SetInfo() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "SetInfo", reflect.TypeOf((*MockINovaLogger)(nil).SetInfo))
}

// SetWarn mocks base method
func (_m *MockINovaLogger) SetWarn() {
	_m.ctrl.Call(_m, "SetWarn")
}

// SetWarn indicates an expected call of SetWarn
func (_mr *MockINovaLoggerMockRecorder) SetWarn() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "SetWarn", reflect.TypeOf((*MockINovaLogger)(nil).SetWarn))
}

// Start mocks base method
func (_m *MockINovaLogger) Start() {
	_m.ctrl.Call(_m, "Start")
}

// Start indicates an expected call of Start
func (_mr *MockINovaLoggerMockRecorder) Start() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Start", reflect.TypeOf((*MockINovaLogger)(nil).Start))
}

// Warning mocks base method
func (_m *MockINovaLogger) Warning(_param0 ...interface{}) {
	_s := []interface{}{}
	for _, _x := range _param0 {
		_s = append(_s, _x)
	}
	_m.ctrl.Call(_m, "Warning", _s...)
}

// Warning indicates an expected call of Warning
func (_mr *MockINovaLoggerMockRecorder) Warning(arg0 ...interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Warning", reflect.TypeOf((*MockINovaLogger)(nil).Warning), arg0...)
}

// Warningf mocks base method
func (_m *MockINovaLogger) Warningf(_param0 string, _param1 ...interface{}) {
	_s := []interface{}{_param0}
	for _, _x := range _param1 {
		_s = append(_s, _x)
	}
	_m.ctrl.Call(_m, "Warningf", _s...)
}

// Warningf indicates an expected call of Warningf
func (_mr *MockINovaLoggerMockRecorder) Warningf(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	_s := append([]interface{}{arg0}, arg1...)
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Warningf", reflect.TypeOf((*MockINovaLogger)(nil).Warningf), _s...)
}

// WithError mocks base method
func (_m *MockINovaLogger) WithError(_param0 error) *logrus.Entry {
	ret := _m.ctrl.Call(_m, "WithError", _param0)
	ret0, _ := ret[0].(*logrus.Entry)
	return ret0
}

// WithError indicates an expected call of WithError
func (_mr *MockINovaLoggerMockRecorder) WithError(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "WithError", reflect.TypeOf((*MockINovaLogger)(nil).WithError), arg0)
}

// WithField mocks base method
func (_m *MockINovaLogger) WithField(_param0 string, _param1 interface{}) *logrus.Entry {
	ret := _m.ctrl.Call(_m, "WithField", _param0, _param1)
	ret0, _ := ret[0].(*logrus.Entry)
	return ret0
}

// WithField indicates an expected call of WithField
func (_mr *MockINovaLoggerMockRecorder) WithField(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "WithField", reflect.TypeOf((*MockINovaLogger)(nil).WithField), arg0, arg1)
}

// WithFields mocks base method
func (_m *MockINovaLogger) WithFields(_param0 log4nova.Fields) *logrus.Entry {
	ret := _m.ctrl.Call(_m, "WithFields", _param0)
	ret0, _ := ret[0].(*logrus.Entry)
	return ret0
}

// WithFields indicates an expected call of WithFields
func (_mr *MockINovaLoggerMockRecorder) WithFields(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "WithFields", reflect.TypeOf((*MockINovaLogger)(nil).WithFields), arg0)
}

// Write mocks base method
func (_m *MockINovaLogger) Write(_param0 []byte) (int, error) {
	ret := _m.ctrl.Call(_m, "Write", _param0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write
func (_mr *MockINovaLoggerMockRecorder) Write(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Write", reflect.TypeOf((*MockINovaLogger)(nil).Write), arg0)
}
